"""Builds tools/jobs/music.json and tools/jobs/sfx.json (text prompts only)."""
import json
from pathlib import Path

M = "src/assets/audio/music/"
S = "src/assets/audio/sfx/"
BASE = ("Instrumental video game soundtrack, retro 16-bit SNES-era fantasy RPG style with rich modern production, "
        "seamless loop, no vocals. ")

MUSIC = [
    ("m_title", 90, "Main title theme: hopeful yet melancholic, a lone music-box and harp melody grows into warm strings and soft choir pads, lantern in the darkness, 80 BPM"),
    ("m_intro", 80, "Story prologue narration underscore: gentle solo piano and cello, sorrowful and tender, slowly swelling strings, 70 BPM, cinematic"),
    ("m_village", 90, "Cozy night village hub: warm acoustic guitar, flute and soft glockenspiel, crackling hearth mood, safe and nostalgic, 90 BPM"),
    ("m_forest", 70, "Enchanted dark forest dungeon: plucked harp and flute melody, soft strings, light hand percussion, mysterious but adventurous, 100 BPM"),
    ("m_crypt", 80, "Underground flooded crypt dungeon: dark ambient choir hums, dripping water percussion, low strings and eerie celesta, tense, 85 BPM"),
    ("m_desert", 80, "Scorching desert ruins: middle eastern oud and ney flute, darbuka percussion, driving and exotic, 110 BPM"),
    ("m_ice", 80, "Frozen cathedral: crystalline bells, pipe organ and airy synth pad, cold and beautiful, sad waltz feeling, 95 BPM"),
    ("m_throne", 80, "Final dungeon hollow throne: ominous pipe organ, low brass, pulsing synth bass and war drums, dark and grand, 105 BPM"),
    ("m_boss", 90, "Intense boss battle: fast driving drums, aggressive electric bass, heroic brass stabs and racing strings, epic JRPG boss fight, 150 BPM"),
    ("m_final", 100, "Final boss battle against the dark king: choir pads, pipe organ, heavy drums and fiery violin lead, desperate and epic, 160 BPM"),
    ("m_victory", 40, "Victory fanfare that settles into a warm triumphant hymn with brass and strings, joyful, 100 BPM"),
    ("m_defeat", 40, "Somber defeat theme: soft piano and distant strings, bittersweet but hopeful, 60 BPM"),
]

SFX = {
    "ui_click": (0.5, "soft short UI button click, wooden tick, game menu"),
    "ui_close": (0.5, "soft UI whoosh close, short"),
    "ui_confirm": (0.6, "bright positive UI confirm chime, fantasy game"),
    "ui_error": (0.5, "short dull error buzz, UI denied"),
    "ui_page": (0.5, "paper page turn swish"),
    "ui_splash": (1.8, "magical shimmering chime swell for a game studio logo"),
    "swing": (0.5, "quick sword swing whoosh"),
    "swing_heavy": (0.6, "heavy sword swing whoosh with metal ring"),
    "thrust": (0.5, "fast spear thrust whoosh stab"),
    "bow": (0.5, "bow string release twang with arrow whoosh"),
    "cast": (0.6, "short magic spell cast sparkle, star magic"),
    "hit": (0.5, "sword hitting a monster, fleshy impact thud, crisp"),
    "hit_heavy": (0.6, "heavy crushing hit impact with crunch"),
    "dash": (0.5, "quick dodge roll whoosh dash"),
    "spin": (0.7, "spinning blade whirlwind whoosh"),
    "nova": (1.0, "magic ice nova burst, crystalline shatter wave"),
    "flare": (1.6, "massive holy light explosion, radiant burst with choir shimmer"),
    "flare_ready": (0.8, "magical charge complete chime, glowing"),
    "potion": (0.8, "drinking a potion gulp and glass clink, healing sparkle"),
    "heal": (0.7, "gentle healing sparkle chime"),
    "coin": (0.5, "single gold coin pickup ding, bright"),
    "pickup": (0.5, "item pickup pop, soft"),
    "ember": (0.5, "glowing ember crystal pickup, warm magical tinkle"),
    "loot_rare": (0.9, "rare item drop, sparkling magical jingle"),
    "loot_legendary": (1.6, "legendary item drop, epic golden shimmer with choir hit"),
    "level_up": (1.2, "level up fanfare jingle, bright ascending arpeggio"),
    "player_hurt": (0.5, "young hero hurt grunt with impact"),
    "player_death": (1.5, "hero falls, dramatic fading impact with low boom"),
    "revive": (1.5, "phoenix rebirth fire whoosh and rising magical tone"),
    "shield_hit": (0.5, "magical shield absorbing a hit, glassy ping"),
    "enemy_death": (0.6, "small monster dies, squishy pop poof"),
    "elite_death": (0.9, "big monster death roar cut short with thud"),
    "boss_death": (2.5, "giant boss monster death roar, collapsing rumble and magical explosion"),
    "enemy_shoot": (0.5, "monster spits a magic projectile, short pew"),
    "enemy_swing": (0.5, "monster claw swipe whoosh"),
    "telegraph": (0.6, "warning charge-up hum, danger"),
    "charge": (0.6, "heavy monster charging stomp rush"),
    "fuse": (0.6, "bomb fuse sizzle"),
    "explosion": (0.9, "fiery explosion boom"),
    "ice_burst": (0.8, "ice shards bursting crackle"),
    "poison_burst": (0.8, "toxic gas bubble burst hiss"),
    "freeze": (0.6, "something freezing solid, ice crackle"),
    "shatter": (0.6, "frozen enemy shattering into ice shards"),
    "zap": (0.5, "electric zap crackle"),
    "thunder": (0.9, "lightning bolt strike thunder crack"),
    "meteor": (1.0, "meteor impact fiery explosion"),
    "smite": (0.7, "holy smite beam strike with bell"),
    "blink": (0.5, "magic teleport blink whoosh"),
    "summon": (0.9, "dark summoning ritual whoosh, eerie"),
    "burrow": (0.8, "creature burrowing through sand and dirt rumble"),
    "spawn": (0.6, "monster spawning from a magic portal, dark whoosh"),
    "break": (0.6, "clay pot breaking shatter"),
    "chest_open": (1.0, "treasure chest creaking open with sparkle"),
    "gate_open": (1.2, "heavy iron portcullis gate rising, chains rattling"),
    "room_clear": (1.2, "triumphant short stinger, room cleared, magical"),
    "step_out": (0.6, "footsteps walking through a doorway, whoosh transition"),
    "descend": (2.0, "descending deeper into a dungeon, deep reverberant rumble with eerie wind"),
    "boon_appear": (1.0, "mystical spirit appearing, ethereal shimmer"),
    "boon_take": (1.0, "gaining magical power, rising sparkle whoosh"),
    "boon_orb": (0.7, "touching a magic orb, bell tone"),
    "relic": (0.9, "picking up an ancient relic, mysterious chime"),
    "shrine": (1.4, "praying at a spirit shrine, soft choir swell"),
    "campfire": (1.5, "crackling campfire, relaxing"),
    "merchant": (0.8, "shop bell ding and coin jingle"),
    "buy": (0.6, "purchase coins clink, fantasy shop"),
    "anvil": (0.8, "blacksmith hammer striking anvil clang"),
    "event_open": (1.0, "mysterious encounter sting, curious"),
    "ambush": (1.0, "ambush alarm sting, monsters appear, tense"),
    "boss_roar": (1.8, "huge monster boss roar, terrifying"),
    "boss_phase": (1.2, "boss enrages, powerful energy surge"),
    "boss_cast": (0.9, "dark boss magic incantation charge"),
    "boss_jump": (0.6, "giant leaping whoosh"),
    "boss_shoot": (0.6, "volley of magic projectiles fired"),
    "slam": (0.9, "massive ground slam earthquake boom"),
    "type": (0.5, "single soft typewriter text blip, retro game dialogue"),
    "quest_complete": (1.4, "quest complete fanfare, short and rewarding"),
    "quest_new": (0.9, "new quest received, parchment and chime"),
    "achievement": (1.2, "achievement unlocked sparkle fanfare"),
    "talent": (0.9, "unlocking a skill talent, magical click and glow"),
    "plant": (0.6, "digging soil and planting seeds"),
    "harvest": (0.8, "harvesting crops, rustle and pop, happy"),
    "forge": (1.2, "forging a weapon, hammer clangs and fire whoosh"),
    "brew": (1.2, "bubbling cauldron brewing potion"),
    "upgrade_fail": (0.8, "failed upgrade, metal crack and sad tone"),
    "door": (0.8, "wooden door opening creak"),
}

Path("tools/jobs").mkdir(parents=True, exist_ok=True)
Path("tools/jobs/music.json").write_text(json.dumps([{"out": M + n + ".mp3", "seconds": s, "prompt": BASE + p} for n, s, p in MUSIC], indent=1))
Path("tools/jobs/sfx.json").write_text(json.dumps([{"out": S + k + ".mp3", "seconds": v[0], "prompt": v[1], "influence": 0.5} for k, v in SFX.items()], indent=1))
print(len(MUSIC), "music", len(SFX), "sfx")
