"""Pack only the 16x16 tiles the game actually references into one small sheet.

The two source tilesets are huge (original_atlas 1792x1280, legacy_atlas 1184x2080, ~19 MB of GPU memory once
decoded), yet rooms and the village use only a few dozen tiles. Every tile reference in the code is a literal
`M(col, row)` (original_atlas) or `LG(col, row)` (legacy_atlas), so this script finds them all, copies those tiles
into public/assets/pack/tiles.png and writes src/data/tileIndex.ts mapping "sheet:index" -> packed frame.

Re-run after adding a tile reference; tests/tiles.test.ts fails if one is missing.
Reads the tilesets straight from the asset master (read-only; nothing is modified there).
"""
import re
from pathlib import Path
from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
ENV = Path("E:/Pixel Games Asset Master/Assets/Gif/Super_Retro_Collection/Resources/Environments")
SHEETS = {"main": ("original_atlas.png", 112), "legacy": ("legacy_atlas.png", 74)}
REF = re.compile(r"\b(M|LG)\((\d+), (\d+)\)")
TILE = 16
COLS = 16


def used_tiles():
    found = set()
    for f in (ROOT / "src").rglob("*.ts"):
        if f.name == "tileIndex.ts":
            continue
        for kind, c, r in REF.findall(f.read_text(encoding="utf-8")):
            sheet = "main" if kind == "M" else "legacy"
            found.add((sheet, int(r) * SHEETS[sheet][1] + int(c)))
    return sorted(found)


def main():
    tiles = used_tiles()
    sources = {k: Image.open(ENV / name).convert("RGBA") for k, (name, _) in SHEETS.items()}
    rows = (len(tiles) + COLS - 1) // COLS
    out = Image.new("RGBA", (COLS * TILE, max(1, rows) * TILE), (0, 0, 0, 0))
    lines = []
    for n, (sheet, i) in enumerate(tiles):
        cols = SHEETS[sheet][1]
        sx, sy = (i % cols) * TILE, (i // cols) * TILE
        out.paste(sources[sheet].crop((sx, sy, sx + TILE, sy + TILE)), ((n % COLS) * TILE, (n // COLS) * TILE))
        lines.append(f"  '{sheet}:{i}': {n},")
    out.save(ROOT / "public" / "assets" / "pack" / "tiles.png", optimize=True)
    ts = [
        "// Generated by tools/pack_tiles.py — do not edit. Maps a tile reference (sheet:index) to its frame in tiles.png.",
        "export const TILE_INDEX: Record<string, number> = {",
        *lines,
        "};",
        "",
    ]
    (ROOT / "src" / "data" / "tileIndex.ts").write_text("\n".join(ts), encoding="utf-8")
    print(f"packed {len(tiles)} tiles into {out.width}x{out.height}")


if __name__ == "__main__":
    main()
