import {chromium} from 'playwright-core';
import fs from 'node:fs';
const dest = decodeURIComponent(new URL('../trailer/public/', import.meta.url).pathname).replace(/^\/([A-Z]:)/,'$1');
const browser = await chromium.launch({channel:'msedge',headless:true,args:['--autoplay-policy=no-user-gesture-required']});
const ctx = await browser.newContext({viewport:{width:540,height:960},deviceScaleFactor:2,hasTouch:true,isMobile:true,recordVideo:{dir:dest+'recordings',size:{width:540,height:960}}});
const page=await ctx.newPage();
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:4174');
await page.waitForFunction(()=>window.__game&&window.__services?.save&&window.__grant);
await page.waitForFunction(()=>['Menu','Onboarding'].some(k=>__game.scene.isActive(k)));
await page.evaluate(()=>{__setLang('en');__services.save.reset();const s=__services.save.data;s.profile.onboardingDone=true;s.profile.introSeen=true;s.profile.tutorialDone=true;__services.notify=()=>{};__game.scene.getScenes(true).forEach(sc=>sc.scene.stop());const r=__run.start({heroId:'rowan'});r.level=7;r.boons=['em_kindle','em_pyre','em_flashfire','em_meteor'].map(id=>({id,rank:2}));__game.scene.start('RunMap');});
await page.waitForTimeout(1200);
await page.evaluate(()=>{const r=__run.run;__game.scene.getScene('RunMap').select(__run.choices(r).find(n=>n.kind==='combat')||__run.choices(r)[0]);__autoplay();});
await page.waitForFunction(()=>__game.scene.isActive('Room'));
await page.waitForTimeout(1400);
await page.screenshot({path:dest+'combat-fresh.png'});
await page.waitForTimeout(14000);
const video=page.video();
await ctx.close();await video.saveAs(dest+'gameplay.webm');await browser.close();
fs.writeFileSync(dest+'capture-report.json',JSON.stringify({errors,source:'Local QA build; real gameplay with prepared level-7 loadout',recordedAt:new Date().toISOString()},null,2));
console.log('Recorded gameplay',errors);
